/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./pages/docs/components/DocumentationSections copy.vue')['default']
    DocumentationCategories: typeof import('./pages/docs/components/DocumentationCategories.vue')['default']
    DocumentationSections: typeof import('./pages/docs/components/DocumentationSections.vue')['default']
    DocumentationUnderSectionList: typeof import('./pages/docs/components/DocumentationUnderSectionList.vue')['default']
    DropdownMenu: typeof import('./common/components/Navigation/DropdownMenu.vue')['default']
    DropdownMenuItem: typeof import('./common/components/Navigation/DropdownMenuItem.vue')['default']
    ErrorAlert: typeof import('./common/components/Alerts/ErrorAlert.vue')['default']
    IconDeviconGithub: typeof import('~icons/devicon/github')['default']
    IconFa6BrandsGithub: typeof import('~icons/fa6-brands/github')['default']
    IconIconoirMenu: typeof import('~icons/iconoir/menu')['default']
    IconIconParkGithub: typeof import('~icons/icon-park/github')['default']
    IconNotoSun: typeof import('~icons/noto/sun')['default']
    IconNotoV1NewMoonFace: typeof import('~icons/noto-v1/new-moon-face')['default']
    IconOouimenu: typeof import('~icons/ooui/menu')['default']
    IconTeenyiconsMoonOutline: typeof import('~icons/teenyicons/moon-outline')['default']
    IconTeenyiconsMoonSolid: typeof import('~icons/teenyicons/moon-solid')['default']
    InfoAlert: typeof import('./common/components/Alerts/InfoAlert.vue')['default']
    MarkdownPlaceholder: typeof import('./pages/docs/components/MarkdownPlaceholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./common/components/Theme/ThemeSwitcher.vue')['default']
  }
}
