/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocsPage: typeof import('./src/pages/DocsPage.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    NotFoundPage: typeof import('./src/pages/NotFoundPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
